package org.ko.generator.constants

object SchemaColumnNameConstants {

  val COLUMN_NAME = "COLUMN_NAME"
  val COLUMN_COMMENT = "COLUMN_COMMENT"
  val DATA_TYPE = "DATA_TYPE"
  val COLUMN_KEY = "COLUMN_KEY"
  val PRI = "PRI"
  val CHARACTER_MAXIMUM_LENGTH = "CHARACTER_MAXIMUM_LENGTH"
  val NUMERIC_PRECISION = "NUMERIC_PRECISION"
  val NUMERIC_SCALE = "NUMERIC_SCALE"
  val TABLE_COMMENT = "TABLE_COMMENT"

}
